server:
  port: 8080

spring:
  application:
    name: authorization-lab

  datasource:
    url: jdbc:postgresql://192.168.3.89:5432/authorization_lab
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: auto